export const normalizeCountryName = (name?: string | null) =>
  String(name ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " and ")
    .replace(/['’().,]/g, "")
    .replace(/-/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();

export const nameMap: Record<string, string> = {
  afghanistan: "af",
  "aland islands": "ax",
  albania: "al",
  algeria: "dz",
  "american samoa": "as",
  andorra: "ad",
  angola: "ao",
  anguilla: "ai",
  antarctica: "aq",
  "antigua and barbuda": "ag",
  argentina: "ar",
  armenia: "am",
  aruba: "aw",
  australia: "au",
  austria: "at",
  azerbaijan: "az",
  bahamas: "bs",
  bahrain: "bh",
  bangladesh: "bd",
  barbados: "bb",
  belarus: "by",
  belgium: "be",
  belize: "bz",
  benin: "bj",
  bermuda: "bm",
  bhutan: "bt",
  bolivia: "bo",
  "bolivia plurinational state of": "bo",
  bonaire: "bq",
  "bonaire sint eustatius and saba": "bq",
  "bosnia and herzegovina": "ba",
  botswana: "bw",
  "bouvet island": "bv",
  brazil: "br",
  "british indian ocean territory": "io",
  "brunei darussalam": "bn",
  brunei: "bn",
  bulgaria: "bg",
  "burkina faso": "bf",
  burundi: "bi",
  "cabo verde": "cv",
  "cape verde": "cv",
  cambodia: "kh",
  cameroon: "cm",
  canada: "ca",
  "cayman islands": "ky",
  "central african republic": "cf",
  chad: "td",
  chile: "cl",
  china: "cn",
  "christmas island": "cx",
  "cocos keeling islands": "cc",
  colombia: "co",
  comoros: "km",
  congo: "cg",
  "congo republic": "cg",
  "republic of the congo": "cg",
  "congo the democratic republic of the": "cd",
  "democratic republic of the congo": "cd",
  "dr congo": "cd",
  "drc": "cd",
  "cook islands": "ck",
  "costa rica": "cr",
  "cote divoire": "ci",
  "cote d ivoire": "ci",
  "ivory coast": "ci",
  croatia: "hr",
  cuba: "cu",
  curacao: "cw",
  cyprus: "cy",
  czechia: "cz",
  "czech republic": "cz",
  denmark: "dk",
  djibouti: "dj",
  dominica: "dm",
  "dominican republic": "do",
  ecuador: "ec",
  egypt: "eg",
  "el salvador": "sv",
  "equatorial guinea": "gq",
  eritrea: "er",
  estonia: "ee",
  eswatini: "sz",
  swaziland: "sz",
  ethiopia: "et",
  "falkland islands": "fk",
  "falkland islands malvinas": "fk",
  "faroe islands": "fo",
  fiji: "fj",
  finland: "fi",
  france: "fr",
  "french guiana": "gf",
  "french polynesia": "pf",
  "french southern territories": "tf",
  gabon: "ga",
  gambia: "gm",
  "the gambia": "gm",
  georgia: "ge",
  germany: "de",
  ghana: "gh",
  gibraltar: "gi",
  greece: "gr",
  greenland: "gl",
  grenada: "gd",
  guadeloupe: "gp",
  guam: "gu",
  guatemala: "gt",
  guernsey: "gg",
  guinea: "gn",
  "guinea bissau": "gw",
  guyana: "gy",
  haiti: "ht",
  "heard island and mcdonald islands": "hm",
  "holy see": "va",
  "vatican city": "va",
  honduras: "hn",
  "hong kong": "hk",
  hungary: "hu",
  iceland: "is",
  india: "in",
  indonesia: "id",
  iran: "ir",
  "iran islamic republic of": "ir",
  iraq: "iq",
  ireland: "ie",
  "isle of man": "im",
  israel: "il",
  italy: "it",
  jamaica: "jm",
  japan: "jp",
  jersey: "je",
  jordan: "jo",
  kazakhstan: "kz",
  kenya: "ke",
  kiribati: "ki",
  korea: "kr",
  "north korea": "kp",
  "korea democratic peoples republic of": "kp",
  "south korea": "kr",
  "korea republic of": "kr",
  kuwait: "kw",
  kyrgyzstan: "kg",
  laos: "la",
  "lao peoples democratic republic": "la",
  latvia: "lv",
  lebanon: "lb",
  lesotho: "ls",
  liberia: "lr",
  libya: "ly",
  liechtenstein: "li",
  lithuania: "lt",
  luxembourg: "lu",
  macao: "mo",
  macau: "mo",
  madagascar: "mg",
  malawi: "mw",
  malaysia: "my",
  maldives: "mv",
  mali: "ml",
  malta: "mt",
  "marshall islands": "mh",
  martinique: "mq",
  mauritania: "mr",
  mauritius: "mu",
  mayotte: "yt",
  mexico: "mx",
  micronesia: "fm",
  "micronesia federated states of": "fm",
  moldova: "md",
  "moldova republic of": "md",
  monaco: "mc",
  mongolia: "mn",
  montenegro: "me",
  montserrat: "ms",
  morocco: "ma",
  mozambique: "mz",
  myanmar: "mm",
  burma: "mm",
  namibia: "na",
  nauru: "nr",
  nepal: "np",
  netherlands: "nl",
  "new caledonia": "nc",
  "new zealand": "nz",
  nicaragua: "ni",
  niger: "ne",
  nigeria: "ng",
  niue: "nu",
  "norfolk island": "nf",
  "north macedonia": "mk",
  macedonia: "mk",
  "northern mariana islands": "mp",
  norway: "no",
  oman: "om",
  pakistan: "pk",
  palau: "pw",
  palestine: "ps",
  "palestine state of": "ps",
  "palestinian territory": "ps",
  panama: "pa",
  "papua new guinea": "pg",
  paraguay: "py",
  peru: "pe",
  philippines: "ph",
  pitcairn: "pn",
  poland: "pl",
  portugal: "pt",
  "puerto rico": "pr",
  qatar: "qa",
  reunion: "re",
  romania: "ro",
  russia: "ru",
  "russian federation": "ru",
  rwanda: "rw",
  "saint barthelemy": "bl",
  "saint helena": "sh",
  "saint helena ascension and tristan da cunha": "sh",
  "saint kitts and nevis": "kn",
  "saint lucia": "lc",
  "saint martin": "mf",
  "saint pierre and miquelon": "pm",
  "saint vincent and the grenadines": "vc",
  samoa: "ws",
  "san marino": "sm",
  "sao tome and principe": "st",
  "saudi arabia": "sa",
  senegal: "sn",
  serbia: "rs",
  seychelles: "sc",
  "sierra leone": "sl",
  singapore: "sg",
  "sint maarten": "sx",
  slovakia: "sk",
  slovenia: "si",
  "solomon islands": "sb",
  somalia: "so",
  "south africa": "za",
  "south georgia and the south sandwich islands": "gs",
  "south sudan": "ss",
  spain: "es",
  "sri lanka": "lk",
  sudan: "sd",
  suriname: "sr",
  "svalbard and jan mayen": "sj",
  sweden: "se",
  switzerland: "ch",
  syria: "sy",
  "syrian arab republic": "sy",
  taiwan: "tw",
  "taiwan province of china": "tw",
  tajikistan: "tj",
  tanzania: "tz",
  "tanzania united republic of": "tz",
  thailand: "th",
  "timor leste": "tl",
  "east timor": "tl",
  togo: "tg",
  tokelau: "tk",
  tonga: "to",
  "trinidad and tobago": "tt",
  tunisia: "tn",
  turkey: "tr",
  turkiye: "tr",
  turkmenistan: "tm",
  "turks and caicos islands": "tc",
  tuvalu: "tv",
  uganda: "ug",
  ukraine: "ua",
  "united arab emirates": "ae",
  "united kingdom": "gb",
  "united states": "us",
  "united states of america": "us",
  "united states minor outlying islands": "um",
  uruguay: "uy",
  uzbekistan: "uz",
  vanuatu: "vu",
  venezuela: "ve",
  "venezuela bolivarian republic of": "ve",
  vietnam: "vn",
  "viet nam": "vn",
  "virgin islands british": "vg",
  "british virgin islands": "vg",
  "virgin islands us": "vi",
  "us virgin islands": "vi",
  "wallis and futuna": "wf",
  "western sahara": "eh",
  yemen: "ye",
  zambia: "zm",
  zimbabwe: "zw",

  ae: "ae",
  "u a e": "ae",
  uae: "ae",
  uk: "gb",
  "u k": "gb",
  gb: "gb",
  usa: "us",
  "u s a": "us",
  us: "us",
  "u s": "us",
};
