export const nameMap = {
  afghanistan: "af",
  "åland islands": "ax",
  albania: "al",
  algeria: "dz",
  argentina: "ar",
  australia: "au",
  austria: "at",
  bahrain: "bh",
  bangladesh: "bd",
  belgium: "be",
  brazil: "br",
  canada: "ca",
  china: "cn",
  denmark: "dk",
  egypt: "eg",
  finland: "fi",
  france: "fr",
  germany: "de",
  ghana: "gh",
  greece: "gr",
  "hong kong": "hk",
  india: "in",
  indonesia: "id",
  iran: "ir",
  iraq: "iq",
  ireland: "ie",
  israel: "il",
  italy: "it",
  japan: "jp",
  jordan: "jo",
  kenya: "ke",
  kuwait: "kw",
  malaysia: "my",
  mexico: "mx",
  morocco: "ma",
  netherlands: "nl",
  "new zealand": "nz",
  nigeria: "ng",
  norway: "no",
  oman: "om",
  pakistan: "pk",
  philippines: "ph",
  poland: "pl",
  portugal: "pt",
  qatar: "qa",
  russia: "ru",
  "saudi arabia": "sa",
  singapore: "sg",
  "south africa": "za",
  "south korea": "kr",
  spain: "es",
  "sri lanka": "lk",
  sweden: "se",
  switzerland: "ch",
  taiwan: "tw",
  thailand: "th",
  turkey: "tr",
  uae: "ae",
  ukraine: "ua",
  "united arab emirates": "ae",
  "united kingdom": "gb",
  "united states": "us",
  uk: "gb",
  usa: "us",
  vietnam: "vn",
  rwanda : "rw",
};
