export const enum SHIPMENT_TYPE {
  DROP_AT_WAREHOUSE = "DROP_AT_WAREHOUSE",
  DOORSTEP_PICKUP = "DOORSTEP_PICKUP",
}

export const enum SHIPMENT_ROUTE {
  AIR_FREIGHT = "AIR_FREIGHT",
  SEA_FREIGHT = "SEA_FREIGHT",
}
