export const enum SHIPMENT_TYPE {
  DROP_AT_WAREHOUSE = "DROP_AT_WAREHOUSE",
  DOORSTEP_PICKUP = "DOORSTEP_PICKUP",
}

export const enum SHIPMENT_ROUTE {
  AIR_FREIGHT = "AIR",
  SEA_FREIGHT = "SHIP",
}


export const enum INFO_UPDATE { 
 EMAIL_UPDATE = "EMAIL_UPDATE",
 PHONE_UPDATE = "PHONE_UPDATE",
 PASSWORD_UPDATE = "PASSWORD_UPDATE"
}

export const enum ABOUT_PAGES {
  TERM_CONDITIONS = "TERM_CONDITIONS",
  PRIVACY_POLICY= "PRIVACY_POLICY",
  ABOUT_COMPANY ="ABOUT_COMPANY"
}